version: '3'

services:
  back-php:
    container_name: back-php
    build:
      context: ./back/php
      dockerfile: Dockerfile

  back-golang:
    container_name: back-golang
    build:
      context: ./back/golang
      dockerfile: Dockerfile
      target: deployment
    restart: always

  back-rust:
    container_name: back-rust
    build:
      context: ./back/rust
      dockerfile: Dockerfile
      target: deployment
    restart: always

  db:
    container_name: db
    build:
      context: ./env/db/mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db-mysql-volume:/var/lib/mysql
      - ./env/db/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bench
      MYSQL_USER: bench
      MYSQL_PASSWORD: bench
    ports:
      - 3306

  proxy-nginx:
    container_name: proxy-nginx
    build:
      context: ./front
      dockerfile: Dockerfile
      target: production
    hostname: proxy-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - back-rust

volumes:
  db-mysql-volume: