version: '3'

services:
  front-react:
    container_name: front-react
    build:
      context: ./env/front/react
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
    volumes:
      - ./front/react/src:/usr/src/app
    environment:
        # Fixes bug where websocket connection is fixed to default port 3000
        - WDS_SOCKET_PORT=0
    depends_on:
      - db

  back-php:
    container_name: back-php
    build:
      context: ./env/back/php
      dockerfile: Dockerfile
    volumes:
      - ./back/php/src:/opt/
    ports:
      - 9000
    depends_on:
      - db

  back-golang:
    container_name: back-golang
    build:
      context: ./env/back/golang
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back/golang/src:/opt/
    ports:
      - 9002
    depends_on:
      - db

  back-rust:
    container_name: back-rust
    build:
      context: ./env/back/rust
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back/rust/src:/opt/
    ports:
      - 9001
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./env/db/mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db-mysql-volume:/var/lib/mysql
      - ./env/db/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bench
      MYSQL_USER: bench
      MYSQL_PASSWORD: bench
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=bench
      - PMA_PASSWORD=bench
    ports:
      - "8080:80"

  proxy-nginx:
    container_name: proxy-nginx
    build:
      context: ./env/proxy/nginx
      dockerfile: Dockerfile
    hostname: proxy-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx:/etc/nginx/conf.d
    depends_on:
      - front-react

volumes:
  db-mysql-volume: